name: Release Core
on: [push]
jobs:
  release-core:
    name: Release Core
    needs: build-project
    runs-on: ubuntu-latest
    steps:
      - name: Create release folder
        run: mkdir -p github-release
      - name: Download Release Core
        uses: actions/download-artifact@v2
        with:
          name: release-core
      - name: Archive Release Core
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "tar"
          filename: "github-release/core.tar.gz"
      - name: Create Release Core
        id: create-new-release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: "github-release/core.tar.gz"
          asset_name: core-v${{ github.run_number }}.tar.gz
          asset_content_type: application/gzip
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload Core Package
        uses: actions/upload-artifact@v2
        with:
          name: release-core
          path: ./sdk/core
