name: Release Core
on: [push]
jobs:
  release-core:
    name: Release Core
    needs: build-project
    runs-on: ubuntu-latest
    steps:
      - name: Download Release Core
        uses: actions/download-artifact@v2
        with:
          name: release-core
      - name: Archive Release Core
        uses: thedoctor0/zip-release@master
        with:
          filename: core.zip
      - name: Create Release Core
        id: create-new-release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - name: Upload Release Asset
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./sdk/core
        # uses: actions/upload-release-asset@v1
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        #   asset_path: ./core.zip
        #   asset_name: core-v${{ github.run_number }}.zip
        #   asset_content_type: application/zip
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload Core Package
        uses: actions/upload-artifact@v2
        with:
          name: release-core
          path: ./sdk/core
